// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("cyphergraph")
	ScopeName = "github.com/clement-casse/otelcol-custom/exporter/cyphergraphexporter"
)

const (
	TracesStability = component.StabilityLevelAlpha
)
