name: Cleanup PR Images

on:
  pull_request:
    types: [closed]

jobs:
  purge-images:
    name: Delete image from ghcr.io
    runs-on: ubuntu-latest
    steps:
      - uses: quartx-analytics/ghcr-cleaner@v1
        with:
          owner-type: user
          repository-owner: ${{ github.repository_owner }}
          repository-name: ${{ github.repository }}
          token: ${{ secrets.GH_PAT }}
          delete-untagged: true
          keep-at-most: 5
          filter-tags: pr-*
          skip-tags: main
